apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-notifications-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-controller
subjects:
- kind: ServiceAccount
  name: argocd-notifications-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argocd-notifications-cm
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  channel-teams-url: "https://gearmentinc.webhook.office.com/webhookb2/da8bc72c-48cb-4434-b7c0-16955b9690c6@92ab7646-e7fe-4eb7-a29b-436d706c0a3d/IncomingWebhook/31784b1ea7e64ce6b9c801cc7d1ab35a/f62080b2-0210-4a9c-ad65-b737537be39a"
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-notifications-controller-metrics
  name: argocd-notifications-controller-metrics
spec:
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app.kubernetes.io/name: argocd-notifications-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: https://gearmentinc.webhook.office.com/webhookb2/1476b39f-9d9f-4d83-9851-ce7ac115ee3c@92ab7646-e7fe-4eb7-a29b-436d706c0a3d/IncomingWebhook/8311c5fc4997482699df869e01e131d7/f62080b2-0210-4a9c-ad65-b737537be39a
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      containers:
        - name: hello-world-pod
          image: arungupta/helloworld-spring-boot:latest
          ports:
            - containerPort: 80
            - containerPort: 443
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: argocd-notifications-cm
#data:
#  service.teams: |
#    recipientUrls:
#      channelName: $channel-teams-url
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: argocd-notifications-secret
#stringData:
#  channel-teams-url: https://gearmentinc.webhook.office.com/webhookb2/1476b39f-9d9f-4d83-9851-ce7ac115ee3c@92ab7646-e7fe-4eb7-a29b-436d706c0a3d/IncomingWebhook/8311c5fc4997482699df869e01e131d7/f62080b2-0210-4a9c-ad65-b737537be39a